version: '2'

services:
  xvzd:
    image: xvezda/xvzd-wargame:1.0
    env_file:
      - .env
    # image: xvzd:0.2
    container_name: xvzd
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    # environment:
    #   - "FLASK_APP=/app/main.py"
    #   - "FLASK_DEBUG=1"
    volumes:
      - ./app:/app
    ports:
      - "80:80"

